module.exports = {
  activeNavCSS: {
    borderLeftWidth: 1 + 'px',
    borderTopWidth: 1 + 'px',
    borderRightWidth: 1 + 'px',
    borderTopLeftRadius: 0.25 + 'rem',
    borderTopRightRadius: 0.25 + 'rem',
    marginBottom: -1 + 'px',
    color: '#495057',
    borderColor: '#dee2e6 #dee2e6 #fff',
  },
  activeNavCSSSettingsPage: {
    border: 1 + 'px',
    borderWidth: 1 + 'px',
    borderRadius: 0.25 + 'rem',
    color: '#495057',
    borderColor: '#edf2f7',
    borderStyle: 'solid',
  },
  CSSTransitionStyle: { color: '#e53e3e', fontSize: 0.75 + 'em' },
  inputTextAreaCSSCreateBid: 'p-2 bg-gray-200 focus:outline-none appearance-none focus:border-gray-500 focus:bg-white border rounded leading-tight ',
  inputTextAreaCSS: 'py-2 px-4  bg-gray-200 focus:outline-none appearance-none focus:border-gray-500 focus:bg-white border rounded leading-tight ',
  navLinkCSS: 'cursor-pointer mr-px bg-white inline-block py-2 px-4 text-blue-500 hover:border hover:rounded-t font-semibold',
  navLinkCSSSettings: 'cursor-pointer mr-px bg-white inline-block py-2 px-4 text-blue-500 hover:border hover:rounded font-semibold',
};
